coverage:
  status:
    project:
      default:
        # Keep the project coverage target to auto
        target: auto
    patch:
      default:
        # Set the patch coverage target to 75%
        target: 75%
